apiVersion: v1
kind: Service
metadata:
  name: agent
  labels: { app: agent }
spec:
  selector: { app: agent }
  ports:
    - name: http
      port: {{ .Values.agent.port }}
      targetPort: {{ .Values.agent.port }}
